CREATE DATABASE IF NOT EXISTS todo_db_carla CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE todo_db_carla;

CREATE TABLE IF NOT EXISTS tasks(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    completed TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);